export const en = {
  brand: {
    name: "Rakshak",
    tagline: "Verify before you trust.",
    positioning: "AI Financial Threat Intelligence for Indian Investors",
  },
  nav: {
    product: "Product",
    how: "How It Works",
    safety: "Safety",
    about: "About",
    cta: "Analyze Content",
    dashboard: "Dashboard",
    settings: "Settings",
    investigate: "Investigate",
    locker: "Locker",
    menu: "Menu",
  },
  common: {
    skipToContent: "Skip to content",
    analyze: "Analyze",
    analyzeSomething: "Analyze Something",
    checkSomething: "Check something",
    seeDemo: "See Demo",
    seeHow: "See How It Works",
    cancel: "Cancel",
    save: "Save",
    saved: "Saved",
    exportReport: "Export Report",
    delete: "Delete",
    back: "Back",
    retry: "Try again",
    copy: "Copy",
    copied: "Copied",
    close: "Close",
    loading: "Loading…",
    language: "Language",
    simpleMode: "Simple mode",
    newAnalysis: "New analysis",
    confidence: "Confidence",
    all: "All",
    none: "None",
    unknown: "Unknown",
    dismiss: "Dismiss",
    optional: "Optional",
    moreInfo: "What does this mean?",
    emptyLocker: "No saved investigations yet.",
    emptyLockerHint: "Run an analysis and save it to build your evidence locker.",
  },
  hero: {
    ctaDemo: "Try a Demo",
    loopLabel: "How Rakshak works: detect, verify, explain, protect",
    headline: "Verify before you trust.",
    sub: "AI-powered financial threat intelligence for India's retail investors.",
    body: "Rakshak analyzes suspicious investment messages, websites, advertisements and financial claims to help Indian investors identify manipulation, impersonation and fraud signals.",
    cta: "Analyze Something",
    secondary: "See How It Works",
    micro: "No sign-up. Files are processed in your session and never uploaded unless you save them.",
  },
  landing: {
    problemKicker: "The problem",
    problemTitle: "Fraud starts with information, not with a transaction",
    problemBody:
      "A message, a forwarded screenshot, a WhatsApp offer, a look-alike website or a voice note arrives before any money moves. Most investors are asked to decide in seconds, with no way to check what they are being told.",
    problemPoints: [
      "Impersonation of regulators, brokers and government bodies",
      "Guaranteed and unrealistic return claims",
      "Urgency, scarcity and pressure to pay immediately",
      "Verification that is technically possible but practically impossible in the moment",
    ],
    howKicker: "How it works",
    howTitle: "Detect. Verify. Explain. Protect.",
    howBody: "Rakshak never answers a single yes-or-no question. It decomposes the content and shows its reasoning at every step.",
    steps: [
      { n: "01", title: "Detect", body: "Extract entities, claims and scam signals from screenshots, messages and URLs." },
      { n: "02", title: "Verify", body: "Check what evidence exists, what can be checked, and what cannot be checked at all." },
      { n: "03", title: "Explain", body: "Show a risk and trust score with the exact reasons behind every point." },
      { n: "04", title: "Protect", body: "Give concrete next steps: what to avoid, what to verify, where to report." },
    ],
    exampleKicker: "Interactive example",
    exampleTitle: "See it interrogate a real message",
    exampleBody: "This is the actual analysis engine, not a screenshot of one.",
    graphKicker: "Trust graph",
    graphTitle: "Every claim, connected to the thing making it",
    graphBody:
      "Instead of a verdict, Rakshak builds an investigation graph: who claims what, who they contact, what they ask you to pay, and which links are verified, unknown or suspicious.",
    bharatKicker: "Bharat-first",
    bharatTitle: "Built for every Indian investor",
    bharatBody:
      "English, हिन्दी and ગુજરાતી out of the box, with a simple mode that replaces technical language with short sentences and clear actions for elderly and low-literacy users.",
    privacyKicker: "Privacy & safety",
    privacyTitle: "Privacy by design",
    privacyBody:
      "Rakshak does not ask for OTPs, passwords or card numbers. Analysis happens in your session; nothing is stored unless you explicitly save an incident to your evidence locker.",
    impactKicker: "Impact",
    impactTitle: "Where this goes",
    impactBody:
      "Financial fraud increasingly starts with information. Rakshak helps investors interrogate that information before acting on it — and gives regulators, educators and helpdesks a shared, explainable language for describing risk.",
    impactStats: [
      { value: "4", label: "Step safety loop" },
      { value: "20", label: "Explainable scam signals" },
      { value: "3", label: "Indian languages at launch" },
      { value: "0", label: "Investment recommendations" },
    ],
    ctaTitle: "Don't ask AI what to invest in.",
    ctaBody: "Ask it what you should verify before trusting anyone.",
    ctaButton: "Analyze Something",
  },
  input: {
    kicker: "Investigate",
    title: "Check something suspicious",
    subtitle: "Upload a screenshot, paste a message or enter a website address.",
    tabScreenshot: "Screenshot",
    tabText: "Message",
    tabUrl: "URL",
    tabDocument: "Document",
    tabVoice: "Voice",
    tabVideo: "Video",
    hintScreenshot: "Drop an image here, or browse. Text in the image is read on your device.",
    hintText: "Paste the message exactly as you received it.",
    hintUrl: "Paste the website address you were asked to open.",
    hintDocument: "PDF document analysis",
    hintVoice: "Audio message",
    hintVideo: "Video message",
    placeholderText:
      "e.g. SEBI approved investment opportunity. Guaranteed 24% monthly returns. Limited 20 seats. Pay ₹2,999 registration fee today.",
    placeholderUrl: "https://example-investment.example",
    browse: "Browse file",
    dropHere: "Drop to upload",
    analyze: "Analyze",
    analyzeCta: "Run analysis",
    privacyNotice:
      "Rakshak analyzes the content you provide. Avoid uploading passwords, OTPs, card numbers, or other sensitive credentials.",
    errorEmpty: "Add something to analyze first.",
    errorTooLarge: "That file is larger than 8 MB. Please use a smaller image.",
    errorType: "That file type is not supported here.",
    errorOcr: "Text could not be read from this image. Paste the text instead — the analysis works the same way.",
    errorUrl: "That does not look like a complete website address.",
    ocrReading: "Reading text from image…",
    ocrDone: "Text extracted",
    extractReview: "Extracted text",
    unsupportedDoc: "PDF parsing is not enabled in this build.",
    unsupportedVoice: "Microphone analysis is not enabled in this build.",
    unsupportedVideo: "Video analysis is not enabled in this build.",
    unsupportedNote: "This input type is part of the roadmap. Use Screenshot, Message or URL for a full analysis now.",
    voiceDictate: "Speak instead",
    voiceListening: "Listening…",
    voiceUnsupported: "This browser does not support speech input.",
  },
  processing: {
    title: "Analyzing",
    stages: {
      normalize: "Analyzing content…",
      entities: "Extracting entities…",
      claims: "Extracting claims…",
      signals: "Checking signals…",
      verify: "Evaluating evidence…",
      risk: "Scoring risk…",
      explain: "Building evidence report…",
      llm: "Checking with model…",
      evidence: "Building evidence report…",
      trust: "Scoring trust…",
      graph: "Mapping relationships…",
    },
    sub: "Every line of this report will show its source.",
  },
  report: {
    kicker: "Analysis report",
    incident: "Incident",
    detectedContent: "Detected content",
    detectedContentHint: "Exactly what was analyzed.",
    riskSignals: "Risk signals",
    riskSignalsHint: "Patterns matched in the content, each with its evidence.",
    claims: "Claims",
    claimsHint: "What the content asserts, and whether that assertion can be checked.",
    entities: "Detected entities",
    trustGraph: "Trust graph",
    evidence: "Evidence",
    evidenceHint: "What supports each conclusion — and what could not be established.",
    why: "Why is this risky?",
    whyHint: "The strongest reasons, in plain language.",
    whatTodo: "What should I do?",
    whatTodoHint: "Concrete steps. This is safety guidance, not legal or financial advice.",
    save: "Save investigation",
    saved: "Saved to evidence locker",
    saveHint: "Stored only in this browser.",
    export: "Export report",
    noSignals: "No known fraud pattern matched this content.",
    noClaims: "No financial claim was detected in this content.",
    noEntities: "No clear entity was identified in this content.",
    contextLabel: "Context",
    signalsDetected: "{count} risk signals detected",
    signalsDetectedOne: "1 risk signal detected",
    evidenceCount: "{count} evidence items",
    evidenceCountOne: "1 evidence item",
    limitationsCount: "{count} verification limitations",
    limitationsCountOne: "1 verification limitation",
    noLimitations: "No verification limitations",
    confidencePrefix: "Confidence",
    liveUnavailable: "Live verification unavailable",
    liveUnavailableBody:
      "Using available evidence only. This build does not query SEBI, NSDL or bank registers in real time.",
    insufficient: "INSUFFICIENT EVIDENCE",
    insufficientBody:
      "Rakshak could not verify enough information to confidently determine the legitimacy of this claim. The risk score has been capped accordingly.",
    insufficientAction:
      "What you can do: verify the entity independently before you act, and treat this result as undetermined rather than safe.",
    unableToVerify: "We couldn't fully verify this",
    unableToVerifyBody:
      "The source could not be checked with the available evidence. This does not mean it is fraudulent — review the detected signals below.",
    lowConfidence: "Confidence is limited",
    disclaimer:
      "This is a risk indicator, not proof of fraud. Rakshak does not provide investment advice, recommendations or price predictions.",
    footerNote: "Generated by the Rakshak analysis pipeline.",
    llmNote: "Language model assisted extraction",
    rulesNote: "Rules and deterministic scoring",
  },
  breakdown: {
    title: "How did Rakshak reach this score?",
    hint: "Every point comes from the detection engine. Select a factor to jump to its evidence.",
    scoreLine: "Risk score: {score} / 100",
    contextAdjust: "Context adjustment ×{mult} — educational or non-soliciting content is down-weighted.",
    evidenceAvailable: "Evidence available",
    evidenceSignals: "{count} signals",
    evidenceSignalsOne: "1 signal",
    verificationLimits: "Verification limitations",
    bandHigh: "High",
    bandMedium: "Medium",
    bandLow: "Low",
    jump: "Show the evidence",
    sumOfFactors: "Sum of factors",
    breakdownOpen: "Show breakdown",
    breakdownClose: "Hide breakdown",
  },
  risk: {
    label: "Risk score",
    trustLabel: "Trust score",
    factorsTitle: "Score factors",
    of: "of 100",
    levels: {
      LOW: { label: "Low concern", line: "No strong fraud pattern detected." },
      MODERATE: { label: "Moderate", line: "Some patterns worth checking before you act." },
      ELEVATED: { label: "Elevated", line: "Verify independently before acting." },
      HIGH: { label: "High risk", line: "Verify before taking action." },
      CRITICAL: { label: "Critical", line: "Do not act on this without independent verification." },
    },
    factors: {
      deceptive_signals: "Deceptive patterns",
      solicitation: "Payment or credential ask",
      verification_gap: "Unverified claims",
      source_credibility: "Source credibility",
      pressure: "Pressure tactics",
    },
    factorHint: "Weighted contribution to the score",
    contextNote: "Educational or news content — signals are read as descriptions, not offers.",
  },
  trust: {
    label: "Trust score",
    overall: "Overall",
    dimensions: {
      identity: "Identity",
      claims: "Claim verification",
      source: "Source credibility",
      payment: "Payment safety",
      evidence: "Evidence quality",
    },
    hint: "How much of this content could actually be checked.",
  },
  phases: {
    before: "Before you pay",
    paid: "If you already paid",
    report: "Report it",
  },
  severity: { critical: "Critical", high: "High", medium: "Medium", low: "Low", info: "Info" },
  status: {
    verified: "Verified",
    unknown: "Unknown",
    suspicious: "Suspicious",
    requires_verification: "Requires verification",
    contradicted: "Contradicted",
    unverifiable: "Cannot verify",
    no_claim: "Not a claim",
    confirmed: "Confirmed in content",
  },
  domainReasons: {
    shortener: "it hides the real address behind a link shortener",
    tld: "it uses a low-cost domain ending often seen on short-lived sites",
    punycode: "it uses a look-alike or non-standard address encoding",
    lookalike: "it borrows a regulator's name without being an official address",
    structure: "the address is unusually long or randomly built",
    insecure: "it was shared over an unencrypted connection",
  },
  entityTypes: {
    company: "Company",
    regulator: "Regulator",
    person: "Person",
    phone: "Phone",
    email: "Email",
    url: "Website",
    domain: "Domain",
    handle: "Handle",
    amount: "Amount",
    percent: "Return",
    payment: "Payment",
    scheme: "Scheme",
    registration_no: "Registration no.",
    date: "Date",
  },
  claimTypes: {
    REGULATORY_APPROVAL: "Regulatory approval",
    GOVERNMENT_AFFILIATION: "Government affiliation",
    GUARANTEED_RETURN: "Guaranteed return",
    FIXED_RETURN: "Fixed return",
    UNREALISTIC_RETURN: "Unrealistic return",
    RISK_FREE: "Risk-free claim",
    DOUBLE_MONEY: "Double your money",
    URGENT_OFFER: "Urgent offer",
    EXCLUSIVE_OPPORTUNITY: "Exclusive opportunity",
    INSIDER_INFORMATION: "Insider information",
    CELEBRITY_ENDORSEMENT: "Celebrity endorsement",
    PAST_PERFORMANCE: "Past performance",
    ZERO_LOSS: "Zero loss",
    PRESSURE_TO_INVEST: "Pressure to invest",
  },
  claimExplain: {
    REGULATORY_APPROVAL:
      "A claim of regulatory approval can normally be checked against a public register. Until it is checked, treat it as unverified.",
    GOVERNMENT_AFFILIATION:
      "Government affiliation is a strong trust signal, which is exactly why it is commonly impersonated.",
    GUARANTEED_RETURN:
      "Legitimate investments carry uncertainty. A guaranteed return removes that uncertainty on paper, which is a well-known warning sign.",
    FIXED_RETURN: "Fixed returns are promised by deposit products, not by market-linked investments.",
    UNREALISTIC_RETURN:
      "Returns far above prevailing market or deposit rates are a primary indicator of a likely fraudulent scheme.",
    RISK_FREE: "All investing carries risk. A risk-free claim about returns is almost never accurate.",
    DOUBLE_MONEY: "Doubling money on a stated timeline is a classic fraud pattern across markets.",
    URGENT_OFFER: "Artificial deadlines are used to stop people from taking time to verify.",
    EXCLUSIVE_OPPORTUNITY:
      "Exclusivity is used to discourage the recipient from consulting anyone else.",
    INSIDER_INFORMATION: "Claiming insider information is both a warning sign and, in many jurisdictions, unlawful.",
    CELEBRITY_ENDORSEMENT:
      "Celebrity association is frequently fabricated. It should be confirmed on the person's official channel.",
    PAST_PERFORMANCE: "Past returns do not indicate future returns, and quoted figures are rarely sourced.",
    ZERO_LOSS: "Same as a risk-free claim: no market-linked product can promise zero loss.",
    PRESSURE_TO_INVEST: "Pressure to decide immediately removes the time needed to verify.",
  },
  signals: {
    guaranteed_return: {
      title: "Guaranteed returns",
      explain:
        "The content promises a fixed return. Legitimate investments involve uncertainty and risk, so a guarantee is a significant warning signal.",
      simple: "⚠️ They are promising you will not lose money. Real investments can go down as well as up.",
    },
    unrealistic_return: {
      title: "Unrealistic return",
      explain:
        "The promised return is far above normal fixed-deposit or market returns, which is one of the most common characteristics of fraudulent schemes.",
      simple: "⚠️ The profit they promise is much higher than anything a bank or honest scheme offers.",
    },
    risk_free: {
      title: "Risk-free claim",
      explain:
        "The content claims there is no risk. Every genuine investment carries some degree of risk, so a no-risk claim cannot be taken at face value.",
      simple: "⚠️ They say you cannot lose. That is not how real investments work.",
    },
    urgency: {
      title: "Urgency",
      explain:
        "You are pushed to act immediately. Urgency is used to prevent you from taking time to verify the sender independently.",
      simple: "⚠️ They want you to act immediately, without thinking.",
    },
    scarcity: {
      title: "Scarcity",
      explain:
        "A limited number of seats, slots or positions is claimed. Manufactured scarcity pressures a fast decision.",
      simple: "⚠️ They say only a few spots are left, to make you hurry.",
    },
    upfront_payment: {
      title: "Upfront payment",
      explain:
        "Money is requested before any service is delivered. Upfront fees for registration, unlocking or activation are a frequent fraud pattern.",
      simple: "⚠️ They are asking for money first. Do not pay before you have verified them.",
    },
    otp_request: {
      title: "OTP request",
      explain:
        "A one-time password or PIN is requested. No genuine broker, bank or regulator ever asks for an OTP.",
      simple: "🚫 Never share an OTP with anyone. No honest company will ever ask for it.",
    },
    credential_request: {
      title: "Credential request",
      explain:
        "Passwords, PINs or account credentials are requested. Sharing them gives someone control of your account.",
      simple: "🚫 Never give your password or PIN to anyone.",
    },
    apk_request: {
      title: "App or file installation request",
      explain:
        "You are asked to install an application or open an unknown file. These are commonly used to take remote control of a phone.",
      simple: "🚫 Do not install any app or open a file they send you.",
    },
    regulatory_impersonation: {
      title: "Regulatory impersonation",
      explain:
        "The content borrows the authority of a regulator such as SEBI, RBI or NSDL. Impersonating a regulator is a serious and common fraud technique.",
      simple: "⚠️ They may be pretending to be a trusted financial organization.",
    },
    government_impersonation: {
      title: "Government impersonation",
      explain:
        "The content claims a government connection. Official bodies do not solicit investments through private messages.",
      simple: "⚠️ They may be pretending to represent the government.",
    },
    identity_ambiguity: {
      title: "Unclear identity",
      explain:
        "No verifiable organisation name, registration number or official address is given, so there is nothing specific to check.",
      simple: "❓ It is not clear who these people are.",
    },
    suspicious_domain: {
      title: "Suspicious website",
      explain:
        "The website shows characteristics associated with short-lived or misleading sites, such as an unusual ending, a recently created address or a look-alike name.",
      simple: "⚠️ This website address does not look trustworthy.",
    },
    mismatched_domain: {
      title: "Mismatched website",
      explain:
        "The domain does not match the organisation it claims to represent, or the brand appears in an unusual part of the address.",
      simple: "⚠️ The website address does not match the company name.",
    },
    social_only: {
      title: "Social-media-only presence",
      explain:
        "The only trace of this entity is on messaging or social platforms, with no verifiable website or official registration.",
      simple: "❓ They only exist on messaging apps, with no real office or website.",
    },
    unverifiable_claims: {
      title: "Unverifiable claims",
      explain:
        "Important assertions are made without any document, register entry or reference that could be checked.",
      simple: "❓ They make big claims but give no proof.",
    },
    pressure_tactics: {
      title: "Pressure tactics",
      explain:
        "The message uses deadlines, consequences or insistence to force a fast decision.",
      simple: "⚠️ They are pressuring you to decide quickly.",
    },
    referral_pressure: {
      title: "Referral pressure",
      explain:
        "You are pushed to bring other people in. Recruitment-based rewards are a structural sign of a pyramid or Ponzi pattern.",
      simple: "⚠️ They want you to bring in more people, which is how these schemes spread.",
    },
    secret_exclusive: {
      title: "Secret or exclusive opportunity",
      explain:
        "The offer is presented as confidential or available to a select few, discouraging you from asking anyone else.",
      simple: "⚠️ They say this is a secret deal just for you.",
    },
    emotional_manipulation: {
      title: "Emotional manipulation",
      explain:
        "Fear, greed, trust or sympathy is used to bypass careful judgement.",
      simple: "⚠️ They are trying to play on your feelings.",
    },
  },
  evidenceStatements: {
    entityUnmatched:
      "{name} could not be confidently matched to verified regulatory information with the data available here.",
    entityAmbiguous: "The only identifier present is “{value}”. No organisation name was given.",
    entityNamed: "The content names “{value}” as the responsible party.",
    domainOfficial: "{value} is on the list of official regulator and market-infrastructure domains used by this build.",
    domainSuspicious: "{value} shows one or more patterns associated with misleading sites ({reason}).",
    domainUnknown: "No reputation data is available for {value} in this offline build.",
    domainFine: "{value} uses a standard address over an encrypted connection.",
    noSource: "No website or contact detail was provided, so the source could not be assessed.",
    regFormatInvalid:
      "The registration number “{value}” does not match the format used by registered Indian market intermediaries.",
    regFormatValid:
      "The registration number “{value}” matches the expected format. Format alone does not prove registration.",
    regFormatNone: "No registration number was supplied to check against intermediary formats.",
    claimUnsupported: "No document, register entry or reference supporting this claim was found in the content.",
    claimQuoted: "Stated directly in the content: “{value}”",
    paymentRequested: "The content asks for {value} before providing access or membership.",
    paymentNoAmount: "The content asks for a payment, without stating an amount.",
    otpQuoted: "A one-time password is requested: “{value}”",
    contactPresent: "A contact identifier was supplied: {value}.",
    externalUnavailable:
      "Verification unavailable: this build has no live connection to the SEBI, MCA or bank registers.",
    contextEducational:
      "The content reads as educational or warning material, so matched patterns were interpreted as descriptions rather than offers.",
    contextNews: "The content reads as news or reporting rather than an offer to you.",
    shortContent:
      "Only {count} characters of content were available, which is not enough for a confident conclusion.",
    noSignals: "No known fraud pattern matched this content.",
    identityMissing: "No person or organisation could be identified as the sender.",
    amountPresent: "A payment amount appears in the content: {value}.",
    urgencyQuoted: "Time pressure appears in the content: “{value}”",
  },
  actions: {
    beforeAvoidTransfer: "Don't transfer money.",
    beforeAvoidOtp: "Don't share OTPs, PINs or passwords.",
    beforeAvoidInstall: "Don't install unknown applications or open files they send.",
    beforeAvoidLink: "Don't open the link or download anything they send.",
    beforeAvoidRecruit: "Don't pay to bring in friends or family.",
    beforeAvoidIdentity: "Don't provide sensitive identity or bank details.",
    beforeDoVerify: "Verify the entity independently through an official channel.",
    beforeDoPreserve: "Preserve the message, screenshots and payment details.",
    beforeDoReport: "Report suspicious activity through official channels.",
    paidBank: "Contact your bank or payment provider immediately.",
    paidTxn: "Preserve transaction references, timestamps and amounts.",
    paidScreens: "Preserve screenshots and the original messages.",
    paidReport: "Follow official cyber-fraud reporting channels.",
    paidStop: "Do not continue communicating with the sender.",
    reportScores: "Check the SEBI SCORES investor grievance portal for registered intermediaries.",
    reportCyber: "Report financial fraud at the national cyber-fraud reporting portal.",
    reportMca: "Verify company incorporation details on the MCA public portal.",
    reportRbi: "Check RBI's regulated-entity lists before depositing money.",
  },
  uncertainties: {
    externalUnavailable:
      "No live registry lookup was possible, so claims were checked against format and consistency only.",
    lowOcr: "Text was read from an image and part of it may be wrong.",
    ambiguous: "There was not enough content to reach a confident conclusion.",
    fetchedTextOnly: "Only the text of the page was read; scripts and embedded media were ignored.",
  },
  why: {
    title: "Why is this risky?",
    hint: "The strongest reasons, in plain language.",
    genericTitle: "Pattern matched",
    claimSource: "Claim detected",
    evidenceSource: "Evidence check",
    contextSource: "Content context",
  },
  graph: {
    scrollHint: "Swipe sideways to explore the whole graph.",
    title: "Trust graph",
    hint: "Select a node to see why it has that status.",
    legend: "Status",
    listView: "List",
    graphView: "Graph",
    empty: "No relationships could be built from this content.",
    relations: {
      CLAIMS: "claims",
      "CLAIMS APPROVAL FROM": "claims approval from",
      "CONTACTS VIA": "contacts via",
      "LINKS TO": "links to",
      "REQUESTS PAYMENT": "requests payment",
      "MENTIONED IN": "mentioned in",
      "ASSOCIATED WITH": "associated with",
      "SUPPORTED BY": "supported by",
    },
    kinds: {
      entity: "Entity",
      claim: "Claim",
      regulator: "Regulator",
      website: "Website",
      phone: "Contact",
      payment: "Payment",
      source: "Source",
      evidence: "Evidence",
    },
    selectPrompt: "Select a node",
    connections: "Connections",
    directionOut: "outgoing",
    directionIn: "incoming",
  },
  inputKinds: { text: "Message", image: "Screenshot", url: "URL", pdf: "PDF", audio: "Voice", video: "Video" },
  demo: {
    title: "Demo mode",
    hint: "Curated scenarios. Deterministic — the same input always produces the same report.",
    run: "Run scenario",
    running: "Running scenario…",
    scenarios: {
      fake_investment: { title: "Fake investment opportunity", desc: "Guaranteed returns with an upfront registration fee." },
      fake_sebi: { title: "Fake SEBI approval", desc: "Regulator impersonation with a fabricated registration number." },
      guaranteed_whatsapp: { title: "Guaranteed-return message", desc: "A forward promising fixed monthly income." },
      fake_broker: { title: "Suspicious broker website", desc: "A look-alike domain with urgency and pressure." },
      gujarati_scam: { title: "Regional-language scam", desc: "The same pattern written in Gujarati." },
      educational: { title: "Educational content", desc: "A legitimate explainer — should not be flagged." },
    },
  },
  dashboard: {
    greetingMorning: "Good morning",
    greetingAfternoon: "Good afternoon",
    greetingEvening: "Good evening",
    title: "Your Investor Safety Center",
    investigations: "Investigations",
    saved: "Saved incidents",
    highRisk: "High-risk findings",
    verifiedClaims: "Verified claims",
    recent: "Recent investigations",
    distribution: "Risk distribution",
    signals: "Common scam signals",
    patterns: "Threat patterns",
    empty: "No investigations yet.",
    emptyCta: "Run your first analysis",
    signalCount: "{count} occurrence",
    signalCountPlural: "{count} occurrences",
  },
  settings: {
    privacyPoints: [
      "Saved investigations live only in this browser's storage. They are never sent anywhere else.",
      "Screenshots and images are read inside your browser with on-device OCR, so the picture never leaves your device.",
      "Text and addresses you submit are analyzed by this app's own API, not by an advertising or tracking service.",
      "Nothing is shared with third parties, and you can delete everything at any time with the button below.",
    ],
    title: "Settings",
    language: "Language",
    languageHint: "Applies to the interface and to generated explanations.",
    simple: "Simple mode",
    simpleHint: "Short sentences, larger text and plain language. Recommended for elderly users and first-time investors.",
    privacy: "Privacy",
    privacyHint: "Investigations are stored in this browser only. Clearing site data removes them.",
    clearData: "Clear saved incidents",
    cleared: "Saved incidents cleared.",
    clearConfirm: "Delete all saved investigations from this browser?",
    roadmap: "Language roadmap",
    roadmapHint: "The architecture is language-agnostic; the next languages are Marathi, Bengali, Tamil, Telugu, Kannada, Malayalam and Punjabi.",
  },
  locker: {
    emptyTitle: "No investigations yet",
    emptyBody: "Analyze something suspicious and save the report — it will appear here, stored in this browser only.",
    title: "Evidence Locker",
    incident: "Incident",
    status: "Status",
    created: "Created",
    input: "Input",
    language: "Language",
    confidence: "Analysis confidence",
    original: "Original input",
    saved: "Saved investigations",
    open: "Open",
    subtitle: "Saved investigations live in this browser only. Nothing is uploaded.",
    search: "Search",
    searchPlaceholder: "Incident number, entity or excerpt",
    all: "All levels",
    sortNewest: "Newest first",
    sortRisk: "Highest risk first",
    noResults: "No saved investigation matches this search.",
    signalsCount: "{count} signals",
    delete: "Remove",
    deleteConfirm: "Remove this investigation from the locker?",
    exportAll: "Export all",
    clearAll: "Clear locker",
    clearConfirm: "Remove every saved investigation from this browser?",
    savedCount: "{count} saved",
  },
  errors: {
    unsupported: "That kind of input cannot be analyzed yet. Try text, a screenshot, or a public address.",
    notFound: "Incident not found",
    notFoundBody: "This investigation is not in this browser's evidence locker.",
    backHome: "Back to home",
    generic: "Something went wrong while analyzing. Try again, or paste the text directly.",
    network: "Could not reach the analysis service. Check your connection and try again.",
    empty: "Nothing to analyze yet.",
  },
  footer: {
    tagline: "Verify before you trust.",
    disclaimer:
      "Rakshak is an investor-safety and verification tool. It does not provide investment advice, recommendations, or predictions of returns.",
    built: "Built for the SANGYAN Hackathon — SNTC, IIT (BHU) Varanasi, in collaboration with SEBI and NSDL.",
    product: "Product",
    resources: "Resources",
    legal: "Safety",
    privacyNotice: "Privacy",
    safetyNote: "No investment advice",
  },
  safety: {
    can: "Rakshak can",
    cannot: "Rakshak will never",
    canItems: [
      "Explain financial terminology",
      "Identify suspicious claims",
      "Explain fraud patterns",
      "Check publicly verifiable claims",
      "Recommend safe verification steps",
      "Explain investor grievance routes",
    ],
    cannotItems: [
      "Recommend stocks or funds",
      "Tell you to buy, sell or hold",
      "Predict prices or returns",
      "Promote brokers or products",
      "Give personalized investment advice",
    ],
  },
};

/**
 * The English dictionary defines the shape. Hindi and Gujarati are typed
 * against it, so a missing or misspelled key is a compile error rather than
 * a runtime `undefined` in front of a user.
 */
export type Dict = typeof en;
